source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TSMessages' do
  pod "TSMessages", :path => "../"
end

target 'Tests' do
  pod "TSMessages", :path => "../"

  pod 'Specta', '~> 0.2.1'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
